#This file is for service2, you need to create an another service file similar to this
#service2.yaml
apiVersion: v1
kind: Service
metadata:
  name: django-app2-service
spec:
  type: ClusterIP
  selector:
    app: django-app2
  ports:
  - port: 80
    targetPort: 8000
